sudo: 'required'

dist: xenial

services: docker

language: bash

env:
    global:
        - QEMU_VERSION=v4.0.0
        - DOCKER_FILE=Dockerfile.alpine
        - BASE=python:3.5-alpine3.10
    matrix:
        - QEMU_ARCH=x86_64   ARCH=amd64
        - QEMU_ARCH=arm      ARCH=arm32v6
        - QEMU_ARCH=arm      ARCH=arm32v7
        - QEMU_ARCH=aarch64  ARCH=arm64v8

before_install:
  - ./.docker/docker.sh prepare

before_script:
    # Set BUILD_VERSION
    - if [ ! -z "${TRAVIS_TAG}" ]; then export BUILD_VERSION=${TRAVIS_TAG}; else export BUILD_VERSION=v1.1.0; fi

script:
    # Build Docker image
    - ./.docker/docker.sh build

    # Test Docker image
    - ./.docker/docker.sh test

    # Push Docker image
    - >
      if [ ! -z "${TRAVIS_TAG}" ]; then
        # Tag Docker image
        ./.docker/docker.sh tag

        # Docker Login
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

        # Push Docker image
       ./.docker/docker.sh push

        # Docker Logout
        docker logout
      fi

jobs:
    include:
        - stage: manifest
          if: tag =~ ^v
          script:
              # Create and push Docker manifest lists
              # Docker Login
              - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

              # Create and Push Docker Manifest Lists to Docker Hub
              - echo "Create manifest list for all docker images."
              - ./.docker/docker.sh manifest-list

              # Docker Logout
              - docker logout

# notify me when things fail
notifications:
    email: true
