sudo: 'required'

services:
  - 'docker'

language:
  - 'bash'

env:
    global:
        - TARGET=raymondmm/miflora-mqtt
        - QEMU_VERSION=v4.0.0
        - OS=alpine
    matrix:
        - DOCKER_FILE=Dockerfile.alpine ARCH=amd64   QEMU_ARCH=x86_64
        - DOCKER_FILE=Dockerfile.alpine ARCH=arm32v6 QEMU_ARCH=arm
        - DOCKER_FILE=Dockerfile.alpine ARCH=arm32v7 QEMU_ARCH=arm
        - DOCKER_FILE=Dockerfile.alpine ARCH=arm64v8 QEMU_ARCH=aarch64

before_install:
  - ./.docker/docker.sh prepare

install: true

before_script:
    # Set BUILD_VERSION
    - >
      if [ ! -z "${TRAVIS_TAG}" ]; then
        export BUILD_VERSION=${TRAVIS_TAG};
      else
        export BUILD_VERSION=v2.3.8;
      fi

script:
    # Build Docker image
    - ./.docker/docker.sh build

    # Test Docker image
    - ./.docker/docker.sh test

    # Push Docker image, ony if TRAVIS_TAG is set
    - >
      if [ ! -z "${TRAVIS_TAG}" ]; then
        # Tag Docker image
        ./.docker/docker.sh tag

        # Docker Login
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

        # Push Docker image
        ./.docker/docker.sh push

        # Docker Logout
        docker logout
      fi

jobs:
    include:
        - stage: manifest
          # Only create and push manifest list to Docker Hub, when tag starts with a `v`, eg. v2.3.8
          if: tag =~ ^v
          script:

            # Create and push Docker manifest lists
            # The push order is displayed in reverse order on Docker Hub

            # Docker Login
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

            # Create and push manifest list `version`
            - ./.docker/docker.sh manifest-list-version

            # Create and push manifest list 'latest' or 'testing'
            - ./.docker/docker.sh manifest-list-testing-or-latest

            # Docker Logout
            - docker logout

# notify me when things fail
notifications:
    email: true
